auctions/urls.py
"""Contains urls for all app's views"""
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("about_us", views.about_us, name="about_us"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("user_panel", views.user_panel, name="user_panel"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("<int:auction_id>", views.listing_page, name="listing_page"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("partners", views.partners, name="partners"), #added for partners page
    path("merch", views.merch, name="merch"), #added for merch page
    path("footprint", views.footprint, name="footprint"), #added for footprint page
    path("purpose", views.purpose, name="purpose"), #added for purpose
    path("bid", views.bid, name="bid"),
    path("categories", views.categories, name="categories"),
    path("categories/<str:category>", views.categories, name="categories"),
    path("close_auction/<str:auction_id>", views.close_auction, name="close_auction"),
    path("handle_comment/<str:auction_id>", views.handle_comment, name="handle_comment")
]

ebdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

handler404 = "auctions.views.handle_not_found"

auctions/models.py
"""Contains all models used in the app."""
from django.contrib.auth.models import AbstractUser
from django.db import models

import sys

class User(AbstractUser):
    """User model - inherited from Django implementation"""
    pass

class Auction(models.Model):
    """Auction model contains all info about one auction:
    * auction's title
    * auction's description
    * who is selling
    * auction's current price
    * when auction was published
    * when will it close
    * what is auction's category
    * auction's image URL
    * is auction closed?
    * partners
    """

    # Categories - choices
    COLLECTION1 = "Genesis"
    COLLECTION2 = "Ghetto Kings"
    COLLECTION3 = "Township Princess"


    CATEGORY = [
        (COLLECTION1, "Genesis"),
        (COLLECTION2, "Ghetto Kings"),
        (COLLECTION3, "Township Princess")
    ]

    # Model fields
    # auto: auction_id
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64, blank=False)
    description = models.TextField(blank=True)
    current_price = models.DecimalField(max_digits=11, decimal_places=2, default=0.0)
    category = models.CharField(max_length=30, choices=CATEGORY, default=COLLECTION1)
    image_url = models.URLField(blank=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    close_date = models.DateTimeField(auto_now_add=False, auto_now=False, blank=True) # added close_date field also need to change to allow for close date to be added not 'auto_now'
    closed = models.BooleanField(default=False)
    

    class Meta:
        verbose_name = "auction"
        verbose_name_plural = "auctions"

    def __str__(self):
        return f"Auction id: {self.id}, title: {self.title}, seller: {self.seller}"

class Bid(models.Model):
    """Bid model contains all info about single bid:
    * price
    * who bid
    * when
    * on what auction
    """

    # Model fields
    # auto: bid_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_date = models.DateTimeField(auto_now_add=True)
    bid_price = models.DecimalField(max_digits=11, decimal_places=2)

    class Meta:
        verbose_name = "bid"
        verbose_name_plural = "bids"

    def __str__(self):
        return f"{self.user} bid {self.bid_price} $ on {self.auction}"

class Comment(models.Model):
    """Comment model contains all info about single comment
    * content
    * who posted
    * when
    * on what auction
    """

    # Model fields
    # auto: comment_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(blank=False)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)
    class Meta:
        verbose_name = "comment"
        verbose_name_plural = "comments"

    def __str__(self):
        return f"Comment {self.id} on auction {self.auction} made by {self.user}"

class Watchlist(models.Model):
    """Watchlist model contains all info about object on watchlist
    * which auction is on watchlist
    * on whose watchlist this auction is
    """

    # Model field
    # auto: watchlist_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")

    class Meta:
        verbose_name = "watchlist"
        verbose_name_plural = "watchlists"
        # Forces to not have auction duplicates for one user
        unique_together = ["auction", "user"]

    def __str__(self):
        return f"{self.auction} on user {self.user} watchlist"

auctions/views.py
"""Contains implementation of all views used in this app"""

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
#from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _
from django import forms
# Error exceptions
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError

from .models import User, Auction, Bid, Comment, Watchlist
from datetime import datetime, date


# ----------------------------------------------------------------------
# ------------------------------  Forms  -------------------------------
# ----------------------------------------------------------------------
class CreateListingForm(forms.ModelForm):
    """Creates form for Auction model."""
    title = forms.CharField(label="Title", max_length=20, required=True, widget=forms.TextInput(attrs={
                                                                            "autocomplete": "off",
                                                                            "aria-label": "title",
                                                                            "class": "form-control"
                                                                        }))
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={
                                    'placeholder': "Describe the digital art",
                                    'aria-label': "description",
                                    "class": "form-control"
                                    }))
    image_url = forms.URLField(label="Image URL", required=True, widget=forms.URLInput(attrs={
                                        "class": "form-control"
                                    }))

    category = forms.ChoiceField(required=True, choices=Auction.CATEGORY, widget=forms.Select(attrs={
                                        "class": "form-control"
                                    }))

    close_date = forms.DateTimeField(label='Close Date (Dd-Mm-Yy Hh:Mm)',
                                          label_suffix=" : ", required=True, disabled=False,
                                          input_formats=["%d-%m-%Y %H:%M"],
                                          widget=forms.DateTimeInput(attrs={'class': 'form-control'}),
                                          error_messages={'required': "This field is required."})
    current_price = forms.DecimalField(label='ETH Value', label_suffix=" : ", widget=forms.NumberInput(attrs={
                                        "class": "form-control"})

    )
                                

    #Can we add close date to be date format? Changed but now not saving....need to filter input so it gets "%d-%m-%Y %H:%M" format.

    class Meta:
        model = Auction
        fields = ["title", "description", "category", "image_url", "close_date"]

class BidForm(forms.ModelForm):
    """Creates form for Bid model."""
    class Meta:
        model = Bid
        fields = ["bid_price"]
        labels = {
            "bid_price": _("")
        }
        widgets = {
            "bid_price": forms.NumberInput(attrs={
                "placeholder": "Bid",
                "min": 0.01,
                "max": 100000000000,
                "class": "form-control"
            })
        }

class CommentForm(forms.ModelForm):
    """Creates form for Comment model."""
    class Meta:
        model = Comment
        fields = ["comment"]
        labels = {
            "comment": _("")
        }
        widgets = {
            "comment": forms.Textarea(attrs={
                "placeholder": "Comment here",
                "class": "form-control",
                "rows": 1
            })
        }

# ----------------------------------------------------------------------
# ------------------------------  Views  -------------------------------
# ----------------------------------------------------------------------
def index(request):
    # """Main view: shows all listings."""
    # Get all auctions descending
    #auctions = Auction.objects.filter(closed=False).order_by("-publication_date")

    return render(request, "auctions/index.html") #{
        #"auctions": auctions
    #})

# -- add a page for partners  -------------------------------------------------- NEED TO ASSESS THE auctions part!!! 

def partners(request):
    return render(request, "auctions/partners.html")

# -- add a page for merch  --- 

def merch(request):
    return render(request, "auctions/merch.html")

# -- add a page for marketplace  --- 

def footprint(request):
    return render(request, "auctions/footprint.html")

def about_us(request):
    return render(request, "auctions/about_us.html")

def purpose(request):
    return render(request, "auctions/purpose.html")

#--------------------------------------------------------------------------------------------------

@login_required(login_url="auctions:login")
def user_panel(request):
    """User Panel view: shows all auctions that user:
        * is currently selling
        * sold
        * is currently bidding
        * won
    """
    # Helpers
    all_distinct_bids =  Bid.objects.filter(user=request.user.id).values_list("auction", flat=True).distinct()
    won = []

    # Get auctions currently being sold by the user
    selling = Auction.objects.filter(closed=False, seller=request.user.id).order_by("-publication_date").all()

    # Get auction sold by the user
    sold = Auction.objects.filter(closed=True, seller=request.user.id).order_by("-publication_date").all()

    # Get auctions currently being bid by the user
    bidding = Auction.objects.filter(closed=False, id__in = all_distinct_bids).all()

    # Get auctions won by the user
    for auction in Auction.objects.filter(closed=True, id__in = all_distinct_bids).all():
        highest_bid = Bid.objects.filter(auction=auction.id).order_by('-bid_price').first()

        if highest_bid.user.id == request.user.id:
            won.append(auction)

    return render(request, "auctions/user_panel.html", {
        "selling": selling,
        "sold": sold,
        "bidding": bidding,
        "won": won
    })

@login_required(login_url="auctions:login")
def create_listing(request):
    """Create Listing view: allows to add new listing through a form."""
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        print(form.errors)
        if form.is_valid():
            # Get all data from the form
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            category = form.cleaned_data["category"]
            image_url = form.cleaned_data["image_url"]
            close_date = form.cleaned_data["close_date"]
            current_price = form.cleaned_data["current_price"]
            # Save a record
            auction = Auction(
                seller = User.objects.get(pk=request.user.id),
                title = title,
                description = description,
                category = category,
                image_url = image_url,
                close_date = close_date,
                current_price = current_price
            )
            auction.save()
        else:
            return render(request, "auctions/create_listing.html", {
                "form": form
            })

    return render(request, "auctions/create_listing.html", {
        "form": CreateListingForm(),
    })

def listing_page(request, auction_id):
    """Listing Page view: shows detailed page of a single auction."""
    # Get current auction if exists
    try:
        auction = Auction.objects.get(pk=auction_id)
    except Auction.DoesNotExist:
        return render(request, "auctions/error_handling.html", {
            "code": 404,
            "message": "Auction id doesn't exist"
        })

    # Get info about bids
    bid_amount = Bid.objects.filter(auction=auction_id).count()
    highest_bid = Bid.objects.filter(auction=auction_id).order_by('-bid_price').first()

    # Show auction only to the winner and the seller if closed
    if auction.closed:
        if highest_bid is not None:
            winner = highest_bid.user

            # Diffrent view for winner, seller and other users
            if request.user.id == auction.seller.id:
                return render(request, "auctions/sold.html", {
                    "auction": auction,
                    "winner": winner
                })
            elif request.user.id == winner.id:
                return render(request, "auctions/bought.html", {
                    "auction": auction
                })
        else:
            if request.user.id == auction.seller.id:
                return render(request, "auctions/closed_no_offer.html", {
                    "auction": auction
                })

        return HttpResponse("Error - auction no longer available")
    else:
         # If user logged in, check if auction already in watchlist
        if request.user.is_authenticated:
            watchlist_item = Watchlist.objects.filter(
                    auction = auction_id,
                    user = User.objects.get(id=request.user.id)
            ).first()

            if watchlist_item is not None:
                on_watchlist = True
            else:
                on_watchlist = False
        else:
            on_watchlist = False

        # Get all the comments
        comments = Comment.objects.filter(auction=auction_id)

        # Check who has made the highest bid
        if highest_bid is not None:
            if highest_bid.user == request.user.id:
                bid_message = "Your bid is the highest bid"
            else:
                bid_message = "Highest bid made by " + highest_bid.user.username
        else:

auctions/templates/auctions/bought.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>Congratulations!</h1> 
    <h3>You bought item: {{ auction.title }} for {{ auction.current_price }} $.</h3>
    Please contect the seller <strong>{{ auction.seller.username }}</strong> and finalize your purchase.

{% endblock %}

auctions/templates/auctions/closed_no_offer.html
{% extends "auctions/layout.html" %}

{% block body %}
<h1>We are very sorry ;(</h1>
<h3>You close auction {{ auction.title }} with no purchase offer.</h3>
Please contact us if you need more information on how to sell on our website effectively.
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container">
    <div class="sub-title">Create NFT</div>

    <form action="{% url 'auctions:create_listing' %}", method="POST">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_title">{{ form.title.label }}:</label>
            {{ form.title }}
        </div>
        <div class="form-group mb-3">
            <label for="id_description">{{ form.description.label }}:</label>
            {{ form.description }}
        </div>
        <div class="form-group mb-3">
            <label for="id_category">{{ form.category.label }}:</label>
            {{ form.category }}
        </div>
        <div class="form-group mb-3">
            <label for="id_image_url">{{ form.image_url.label }}:</label> <!-- need to add in location of NFT, S3 bucket? -->
            {{ form.image_url }}
        </div>
        
        <div class="form-group mb-3">
            <label for="id_close_date">{{ form.close_date.label }}:</label>
            {{ form.close_date }}
        </div>

        <!--The above form field has been added, how do I ensure its added to database? Views and then ensure added to admin/ models-->
        <div class="form-group mb-3">
            <label for="id_value">{{ form.current_price.label }}:</label>
            {{ form.current_price }}
        </div>
        <!--Needs more work to add to form only showing : -->
        <button type="submit" class="btn btn-primary btn-new-purple" aria-label="submit">Submit</button>
        
    </form>
    <br/>
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}   

{% url 'auctions:index' as  home %}
{% url 'auctions:categories' category='Genesis' as  COLLECTION1 %}
{% url 'auctions:categories' category='Ghetto Kings' as  COLLECTION2 %}
{% url 'auctions:categories' category='Township Princess' as  COLLECTION3 %}
{% url 'auctions:about_us' as about_us %}
{% url 'auctions:merch' as merch %}
{% url 'auctions:footprint' as footprint %}

<!-- Sort URLS 
ZNMFDQT - Genesis
IQNFYQY - Ghetto Kings
ZQDUZLPA - Township Princess
-->

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}inkeDama - Orphan Art for Impact{% endblock %}</title>
    <link rel="icon" href="{{files_path}}/img/inkedama-logo-small.png" type = "image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7faee5c6e1.js" crossorigin="anonymous"></script>
    <link href="{{files_path}}/css/styles.css" rel="stylesheet">
    <link href="{{files_path}}/css/sidebar.css" rel="stylesheet">
    <script defer src="{{files_path}}/js/sidebar.js"></script>
    <script>
        function copyOpenSeaAc() {
        /* Get the text field */
        var copyText = document.getElementById("myInput");

        /* Select the text field */
        copyText.select();
        copyText.setSelectionRange(0, 99999); /* For mobile devices */

        /* Copy the text inside the text field */
        navigator.clipboard.writeText(copyText.value);
  
        /* Alert the copied text */
        //alert("Kuhle (Xhosa for awesome!) you have copied the Inkedama account number: paste it into the Open Sea search bar to find us");

    }
    </script>
</head>

<body>
    <body id="body-pd">
        <!-- Sidebar by  BBBootstrap Team -->
        <header style="height:75px;" class="header" id="header">
            <div style="color:white;" class="header_toggle">
                <i class='fas fa-chevron-right' id="header-toggle"></i>
            </div>
            
            <div>
                <a href="{{ home }}"><img style="height:60px;position:absolute;left:48.5%;top:5px;" src="{{files_path}}/img/inkedama-logo-concept.png"></img></a>
            </div>
            <div class="nav-buttons">
                {% if user.is_authenticated %}
                        <div class="row row-cols-auto">
                            <a class="btn btn-primary btn-new-black" style="margin-left:6px;" href="{% url 'auctions:user_panel' %}">Dashboard</a>
                            
                            <!-- only superusers can create NFTs -->
                            {% if user.is_superuser %}
                                <a class="btn btn-primary btn-new-black" style="margin-left:6px;" href="{% url 'auctions:create_listing' %}">Create NFT</a>
                            {% endif %}
                        
                            <!-- function works, despite VS Code's insistence that it's a syntax error -->
                            <a class="btn btn-primary btn-new-black" style="margin-left:6px;" onclick='return confirm("Are you sure, you want to log out?")' href="{% url 'auctions:logout' %}">
                                <i class='fas fa-sign-out-alt'></i>
                            </a>
                        </div>
                        <strong class="row row-cols-auto" style="color:white;float:right;">
                            Signed in as: {{ user.username }}
                        </strong>
                {% else %}
                    <div class="row row-cols-auto">
                        <a class="btn btn-primary btn-new-black" style="margin-left:6px;" href="{% url 'auctions:login' %}">Log In</a>
                        <a class="btn btn-primary btn-new-black" style="margin-left:6px;" href="{% url 'auctions:register' %}">Register</a>
                    </div>
                {% endif %}
            </div>
        </header>

        


        <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div>
                    <div class="nav_list">
                        <a href="{{ home }}" class="nav_link {% if request.path == home %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <polyline points="5 12 3 12 12 3 21 12 19 12"></polyline>
                                <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                             </svg>
                             <span class="nav_name">Home Page</span> 
                        </a>
                        
                        <a href="{{ COLLECTION1 }}" class="nav_link {% if request.path == COLLECTION1 %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-palette" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M12 21a9 9 0 1 1 0 -18a9 8 0 0 1 9 8a4.5 4 0 0 1 -4.5 4h-2.5a2 2 0 0 0 -1 3.75a1.3 1.3 0 0 1 -1 2.25"></path>
                                <circle cx="7.5" cy="10.5" r=".5" fill="currentColor"></circle>
                                <circle cx="12" cy="7.5" r=".5" fill="currentColor"></circle>
                                <circle cx="16.5" cy="10.5" r=".5" fill="currentColor"></circle>
                             </svg>
                             <span class="nav_name">NFT Collections</span>
                        </a>

                        <a href="{{ merch }}" class="nav_link {% if request.path == merch %} active {% endif %}">
                            <div class="icon icon-tabler icon-tabler-briefcase">
                                <i class='fas fa-tshirt'></i>
                            </div>
                            <span class="nav_name">Merch</span>
                        </a>

                        <a href="{{ footprint }}" class="nav_link {% if request.path == footprint %} active {% endif %}">
                            <div class="icon icon-tabler icon-tabler-briefcase">
                                <i class="fas fa-shoe-prints"></i>  
                            </div>
                            <span class="nav_name">Footprint</span>
                        </a>      

                        <a href="{{ about_us }}" class="nav_link {% if request.path == about_us %} active {% endif %}">
                            <div class="icon icon-tabler icon-tabler-briefcase">
                                <i class="fas fa-question"></i>
                            </div>
                        <span class="nav_name">About the B Corp Collab</span>
                        </a>

                    </div>
                </div>
            </nav>
        </div>

        <div style="min-height:400px;" class="height-auto bg-light">
            {% block body %}

            {% endblock %}
        </div>

        <div class="container-footer w-container">
            <div class="w-row">
                <div class="footer-column w-clearfix w-col w-col-4">
                    <h3 class="footer-failory-name">Inkedama</h3>
                    <p class="footer-description-failory">Inkedama is a collaboration trading name of<a href="https://www.nudgeexchange.com/#/" target="_blank"><span class="footer-link"> Nudge<br></a>Registered Limited Company: SC460309</p>
                    <p class="footer-description-failory">and<a href="https://www.facebook.com/siyakhathalawecare" target="_blank"><span class="footer-link"> Siyakhathala Orphans NPO 068-260<br></span></a><br></p>
                </div>
                
                <div class="footer-column w-col w-col-8">
                <div class="w-row">
                    <div class="w-col w-col-8">
                    <div class="w-row">
                        <div class="w-col w-col-7 w-col-small-6 w-col-tiny-7">
                        <h3 class="footer-titles">Learn</h3>
                        <p class="footer-links">
                            <a href="https://metamask.io/faqs" target="_blank"><span class="footer-link">Metamask<br></span></a>
                            <a href=""><span class="footer-link"></span></a>
                            <a href="https://support.opensea.io/hc/en-us" target="_blank"><span class="footer-link">Open Sea<br></span></a>
                            <a href="https://rarible.com/how-it-works" target="_blank"><span class="footer-link">Rarible</span></a><strong><br></strong></p>
                        </div>

                        <div class="w-col w-col-5 w-col-small-6 w-col-tiny-5">
                        <h3 class="footer-titles">Other</h3>
                        <p class="footer-links">
                            <a href="{% url 'auctions:partners' %}"><span class="footer-link">Our Partners<br></span></a>
                            <a href="{% url 'auctions:purpose' %}"><span class="footer-link">Inkedama Purpose<br></span></a>
                            <a href="{% url 'auctions:footprint' %}"><span class="footer-link">Footprint</span></a>
                        </p>
                        </div>
                    </div>
                    </div>
                    <div class="column-center-mobile w-col w-col-4">
                    <!-- <h3 class="footer-titles">Follow us for our next drops!</h3><a href="" target="_blank" class="footer-social-network-icons w-inline-block"><img src="https://uploads-ssl.webflow.com/5966ea9a9217ca534caf139f/5c8dbf0a2f2b67e3b3ba079c_Twitter%20Icon.svg" width="20" alt="Twitter icon"></a><a href="" target="_blank" class="footer-social-network-icons w-inline-block"><img src="https://uploads-ssl.webflow.com/5966ea9a9217ca534caf139f/5c8dbfe70fcf5a0514c5b1da_Instagram%20Icon.svg" width="20" alt="Instagram icon"></a><a href="" target="_blank" class="footer-social-network-icons w-inline-block"><img src="https://uploads-ssl.webflow.com/5966ea9a9217ca534caf139f/5c8dbe42e1e6034fdaba46f6_Facebook%20Icon.svg" width="20" alt="Facebook Icon"></a><a href="" target="_blank" class="footer-social-network-icons w-inline-block"><img src="https://uploads-ssl.webflow.com/5966ea9a9217ca534caf139f/5c8dc0002f2b676eb4ba0869_LinkedIn%20Icon.svg" width="20" alt="LinkedIn Icon"></a><a href="" target="_blank" class="footer-social-network-icons w-inline-block"><img src="https://uploads-ssl.webflow.com/5966ea9a9217ca534caf139f/5c8dc0112f2b6739c9ba0871_Pinterest%20Icon.svg" width="20" alt="Pinterest Icon" class=""></a> -->
                    <h3 class="footer-titles">Email us at: </h3>
                    <p class="footer-description"><a href=mailto:darren@nudgeexchange.com? target="_blank"><strong class="link-email-footer">darren@nudgeexchange.com</strong></a><br></p>
                    <p class="footer-links">Made with <img src="{{files_path}}/img/heart.svg" width="20" alt="Heart icon"> by <a href="https://www.nudgeexchange.com/#/" target="_blank"><span class="footer-link"> Nudge<br></span></a></p>
                    <img src="{{files_path}}/img/B-Corp-Logo-White.jpg" width="80" alt="B Corp">

                </div>
                </div>
            </div>
        </div>
    </body>

</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="container">
        <div class="sub-title">Login</div>
    
        {% if message %}
            <div class="mb-3">{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'auctions:login' %}" method="post" class="mb-3">
            {% csrf_token %}
            <div class="mb-3">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <input class="btn btn-primary btn-new-blue" type="submit" value="Login">
        </form>
        Don't have an account? <a href="{% url 'auctions:register' %}"><u>Register here.</u></a>

    </div>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="container">
        <div class="sub-title">Register</div>

        {% if message %}
            <div class="mb-3">{{ message }}</div>
        {% endif %}

        <form action="{% url 'auctions:register' %}" method="post" class="mb-3">
            {% csrf_token %}
            <div class="mb-3">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="mb-3">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary btn-new-blue" type="submit" value="Register">
        </form>

        Already have an account? <a href="{% url 'auctions:login' %}" class="anchor_login_text"><u>Log In here.</u></a>
        </div>
{% endblock %}